sudo: required
language: android
jdk: oraclejdk8

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"

android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-28.0.2
  - android-28

before_install:
- echo $deploy_password | gpg --passphrase-fd 0 keystore.jks.gpg
- yes | sdkmanager "platforms;android-28"
- chmod +x gradlew

script:
- ./gradlew clean assembleRelease test

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: p+dbCE9zCUpkUEQGdMKnrQraKQVT/Iy4UnWUinI/cZU3ehkB/yIYvxteS38v3IGNZ3tA1z/4a/BfGJ/EJME0SOkKXfaF6ZpoQRHl/gH+1uLRNY2XUDpFWvLE4KOHp6byF21j3Mq/c7h656/q4TxL/++E1TVXPCSDVONrGphcK2bcmGikhkGm58KQkci95ioyeSTgE8dTWw1KSKBsJBXQQ90m92ZA+rFFFA2uHQ/4n8iGKajpVyFPqi+QFDUEPXp4/QyXSQQAXFt7w+w7Huqr2fkQcTNZqhBMzly1kQafHM/EEACpV2rNWqnO41dNkYR1WVGpItpVhhqCJSJ5OSYVr0C/UMJ4WgapnTFjxtOXy9Rm14/mBY6VjxJ/PMAvTbmdw3g9RqTYF5Yj8rs2gff4862vU8n0+iS9CIewlfBmokYu48x9bPUZMP12EqqLFJuWtrmsIkrsF7dHmOy2ktKxi4JytloYnpALJmja7GwRczY4Jp0LjgIYpz5qv0QOs+7uMVa35gXNjwLVDt69lCzII4tbZI4ejjiQqKFeXaxD3O/pfwwxOot2cnRK4gRkEft+L6zj77Ht1rF6bUKFPKT4j7bIvImZDO+8uesbdSm9f+RY7ew1p/1NF1Eo4K03o/XmI3miSTs/ds05bqBuBzeyKU2v9rQD+L0hqIRE52BKZqM=
  file: android/release/android-release.apk
  on:
    repo: AscendingGames/DungeonCreator
    branch: development
env:
  global:
  - secure: f+smlfUFxxXGySw1FHW9AYID7kFGl4hyoH5uOWGkZGLikK0csoZDuZn4NPUVCUpjaLgGADiyAKca6HTayqIP8/hpwsvjzT57YdVLNwgxf3KpUJo6vkpdkp1M1MXHqo6gMNeQ+y6hF0v1GNSl9vJjX3zknTIkzL87d4pSGFWcYgtk7S0niyz1diUtYL/e6MAKyJATGBKO5MfZs1agqHxOyD+zGpX4ogoVen211FmE9O5UkwEecER1ZRJpBRgOl6dQpkGlcXJQBtavLMyF1NxogqUJPw54OLST97d4BBM8UO4jCW28gY5Xeli1zgcdG5aWPE7BYqbe6l0y+QjzvAWHZUgG6bAFyybPHxERhyyIuPcCpx8N4pcWJiujR6AZjv4Nvus92PzS7ZdirJpCEioD+ZTF0Umr4QSssMQDhouwPg/L3QD/J1nlrqHcBqygnvAZMvzX2/zlYru/JWdjYWIv1I6ZTJXQyPXM4quYMrUbWBZ3AycM0Aotk8Qz0lkeGsVxe3SVcB1l/CZGlRxT6mkVmUcYezeaNPekwPrBShjx5pqcKKLLmwebom+OjE+vsN4qrg8b7wTIEYtMpX/Xstr0i2zTj+wiVRY/yJc7mGN3/6xjgwJVxWvfdyMZB2BzwOscIsPG3wQGZtEwlazB2uwaiqsaCSmwM2OpDCzqdphmpeg=
  - secure: CQ/P9T8nZ9xP9CS473tdCEWmzPTWRR32rKyz26yQDG2e91mgte6XIVkwkFOzt1UdbZYDGOCg9nvwWFItSlHBxfWrHHa1xPbyFVJhiCbU3M/SRBDXaQRtMwKFrqXwGFtNJYjFT0OF282nJH+eKW7TXOpeeCWnEJ4Cq8jpSsf4G9wpfeMsHd1puOzqjqDPOfLtbnRlmmH+XyqXoTjtzQoQJ1I92vXZ85X/9fT1Jw3oge8TC2c9F+5u5tdGt68A5eA8d37xU0GEPSLZRq2zOzyN+YcOzNz4ZT+MwVhWqGDL8bmoZr+YyR/HbUUIZ1uJvgn/Bh+A9yHOEcJel72G/GmZLSwHk3UiVx993B47SurbMAQq92XVRL4rOA0cD12QRZNZMJoatlHoDBD4eadw7yMiZNcLCwSfZgfId+bpRFkjk/4FmcILZ7EaBQfOsH9U8khIcSThLtMLFWBz0X3Md1psQ2EvaLW57Y3CxvHQ6V0A7xDCui8byw1iQP+12IjB1uT/tqC655y1ncm+mBslk8HrQC+XwKuyeJPVBNt9qtHIR5E55Mo4mrpa/YJCaGvZfJH/9f5N1XfpENl7z5X5qa/EX03zryUlSk8vOK9jVGcQqI1giQbZ9buegSv4XksZO4PQV2z7LxrUHm6kFyI4/6FwXMM742Hq95HfYWjQy/sfrDc=
  - secure: EmgSCBOV171LDkpimelDYX1SOQC0BzXyB0zA9wEfHN9krASW60eLjVNRsapVm5Bd24SAcnbnSM4Dl80uu5hS6N709n+NDWfVQ2fkmVHkKrT2DxnL/RSrrLgnHkZp1nPuG9zssD8tNW45vllKCYYfeLSUUx7zlGtYr0vX4NePiuN/jvUBVAnBqTbYr92uRRqduLtxpco3nqKYctVjoUjTckBx1V+Sv1Ue/2n8k8wU3VeV1ILKSDvnnc5CvynMcTaY3moHitfGraAIgkZWHpEuuoa9KcOsa/PzsWEbztFb1ocnY9UwzrkXMx2G5Tmad4jB+X0E/yPa4p6Zz6Mou6hqFxrWP3zCN00htdDKDtmg56Aqqky2eSTdDW87EDMOyUcL/vmkDU2J09Y83QKYvOUJVHW5qFwTl6ZDLJzarQQi/tw3dHlnpD7O3ZTUclv1pRQN8B5FQzipUnUti4WfAvgce12Fh87jXAL4eaRE3p2uxggFWg2I+K4fL1Vj2ogOWsxXDxpVpRPpTu7bJ4EnU7rVRekazBmxy9OwE03GI2OHfIkQ5UG+ajRGewuyNEiDZhmU/wkr5FDRbfMpqcF5PkTqR9coixj20kUS5R0AJ+DlJ4MOZcAT7NLCvSPKO9NxkQd1gEiLxEZ2ZNqNVH9CRW1xnbmUBZ2DjWQ0bsnGmf4X86w=
