# Tag last commit as 'latest'.

if [ "$TRAVIS_BRANCH" = "development" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
  git config --global user.email "hi@travis-ci.org"
  git config --global user.name "Sr. Travis"

  git remote add release "https://${GH_TOKEN}@github.com/AscendingGames/DungeonCreator.git"

  git push -d release development
  git tag -d development
  git tag -a "development" -m "[Autogenerated] This is the latest version pushed to the development branch."
  git push release --tags
fi
